*** Starting uWSGI 2.0.18 (64bit) on [Fri Apr 17 13:40:50 2020] ***
compiled with version: 5.4.0 20160609 on 17 April 2020 05:19:45
os: Linux-4.4.0-177-generic #207-Ubuntu SMP Mon Mar 16 01:16:10 UTC 2020
nodename: we
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/frankie/uptane-django/uptane_django
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 15650
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:29000 fd 3
Python version: 3.8.2 (default, Apr 17 2020, 11:44:35)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: ./../env
Set PythonHome to ./../env
Python main interpreter initialized at 0x12e4500
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Creating '/home/frankie/uptane-django/director_repo/democar'
Creating '/home/frankie/uptane-django/director_repo/democar/metadata.staged'
Creating '/home/frankie/uptane-django/director_repo/democar/targets'
'timestamp.json' expires Sat Apr 18 05:40:57 2020 (UTC).
1.0 day(s) until it expires.
Creating '/home/frankie/uptane-django/image_repo'
Creating '/home/frankie/uptane-django/image_repo/metadata.staged'
Creating '/home/frankie/uptane-django/image_repo/targets'
'timestamp.json' expires Sat Apr 18 05:40:57 2020 (UTC).
0.9999305555555555 day(s) until it expires.
WSGI app 0 (mountpoint='') ready in 13 seconds on interpreter 0x12e4500 pid: 13646 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 13646, cores: 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Aug 14 09:04:53 2020] ***
compiled with version: 5.4.0 20160609 on 14 August 2020 00:32:28
os: Linux-4.4.0-185-generic #215-Ubuntu SMP Mon Jun 8 21:53:19 UTC 2020
nodename: we
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /home/frankie/uptane-django/uptane_django
detected binary path: /home/frankie/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 31777
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:29000 fd 3
Python version: 3.8.0 (default, Aug 13 2020, 21:28:22)  [GCC 5.4.0 20160609]
PEP 405 virtualenv detected: ./../env
Set PythonHome to ./../env
Python main interpreter initialized at 0x2233780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Creating '/home/frankie/uptane-django/image_repo'
Creating '/home/frankie/uptane-django/image_repo/metadata.staged'
Creating '/home/frankie/uptane-django/image_repo/targets'
'timestamp.json' expires Sat Aug 15 01:04:58 2020 (UTC).
0.9999537037037037 day(s) until it expires.
WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x2233780 pid: 19966 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 19966, cores: 1)
Traceback (most recent call last):
  File "/home/frankie/uptane-django/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/home/frankie/uptane-django/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 19966|app: 0|req: 1/1]  () {14 vars in 453 bytes} [Fri Aug 14 04:38:15 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/home/frankie/uptane-django/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 132, in __call__
    request = self.request_class(environ)
  File "/home/frankie/uptane-django/env/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 80, in __init__
    self.method = environ['REQUEST_METHOD'].upper()
KeyError: 'REQUEST_METHOD'
[pid: 19966|app: 0|req: 2/2]  () {14 vars in 376 bytes} [Fri Aug 14 04:38:16 2020]   => generated 0 bytes in 0 msecs ( 500) 0 headers in 0 bytes (0 switches on core 0)
